-- 0004 — Seeds inventory for focus-tier rewards.
--
-- The 5-minute gate + duration-tier rules in src/lib/farmRules.ts award
-- bonus seeds for sessions ≥ 15 minutes (1/2/3 seeds per t15/t30/t50
-- tier). Up to this migration, seeds lived only in the client (the
-- local useFarmStore.seeds field); they did not survive a fresh device.
--
-- This migration extends `farm_inventory` with a `seeds` column so the
-- worker can persist the bonus. Backwards-compatible:
--   - Default 0 on new rows AND on existing rows after ALTER ADD.
--   - Older clients that don't send seedDelta on /farm/grow simply
--     leave the column at its current value.
--
-- SQLite (D1) does not support `ADD COLUMN IF NOT EXISTS`. Wrangler
-- tracks applied migrations in the `d1_migrations` table — running this
-- file twice will fail the ALTER on the second run, which is the
-- standard "already applied" signal. Do NOT edit this file after it has
-- been applied to a remote DB; write a new 0005 instead.

ALTER TABLE farm_inventory ADD COLUMN seeds INTEGER NOT NULL DEFAULT 0;
